name: sli
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adwaita-icon-theme=48.1
  - alsa-lib=1.2.14
  - aom=3.9.1
  - asttokens=3.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attr=2.5.1
  - black=25.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - click=8.2.1
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - double-conversion=3.3.1
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.5
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gprof2dot=2024.6.6
  - graphite2=1.3.14
  - graphviz=13.1.0
  - gtk3=3.24.43
  - gts=0.7.6
  - harfbuzz=11.2.1
  - hicolor-icon-theme=0.17
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - isort=6.0.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.23.0
  - libabseil=20250127.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.7
  - libclang13=20.1.7
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.7
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libudev1=257.7
  - libunwind=1.6.2
  - liburing=2.10
  - libusb=1.0.29
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mpg123=1.32.9
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.61.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.1
  - packaging=25.0
  - pango=1.56.4
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=27.0.0
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - scipy=1.16.0
  - sdl2=2.32.54
  - sdl3=3.2.16
  - segno=1.6.6
  - six=1.17.0
  - snappy=1.2.1
  - stack_data=0.6.3
  - svt-av1=3.0.2
  - tbb=2022.1.0
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7

